// !

const temIngresso = false;

// NÃO É NECESSARIO DETERMINAR  SE É TRUE O FALSE NA LINHA, SEMPRE SERA TRUE AUTOMATICO
// O ! INVERTE A O VALOR DA VARIAVEL - EXEMPLO, COLOCAMOS COMO FALSE (SEM INGRESSO E ELE IMPRIME COM INGRESSO)
// NO CONST ELE ESTA COMO FALSE, NA LINHA ELE VIRA TRUE POR CAUSA DO !
if (!temIngresso) {
    console.log("Possui Ingresso")
}